[package]
name = "blog"
version = "0.1.0"
authors = ["0ersted <zhsang@link.cuhk.edu.hk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
